### ISSUE TITLE
Add netlify icon

### ISSUE THREAD

**Issue by benjithorpe** [rahulbanerjee26/githubProfileReadmeGenerator#15]

**Comment by GuyEternal** [comment]
I can do that

**Comment by GuyEternal** [comment]
@rahulbanerjee26 I can do this if I may.

**Comment by rahulbanerjee26** [comment]
@GuyEternal for sure, go ahead!

**Comment by GuyEternal** [comment]
@rahulbanerjee26 I have added a [PR](https://github.com/rahulbanerjee26/githubProfileReadmeGenerator/pull/18):

**Comment by rahulbanerjee26** [comment]
Icon has been added

**Comment by benjithorpe** [comment]
Thanks a lot, guys.
Really appreciate the effort
